defaults: &defaults
  adapter: sqlite3
  username: root
  password: 
  host: localhost

development:
  database: db/metrics_site_development.db
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/metrics_site_test.db
  <<: *defaults
production:
  database: db/metrics_site_production.db
  <<: *defaults
